addons:
  firefox: "44.0"

language: java

jdk:
  - oraclejdk8

before_install:
  - rvm install 2.4.1

install:
  - gem install octokit

script:
  - ./gradlew clean testIntegration

after_script:
  - ruby ./scripts/publish-gh-pages.rb
